name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.2.1
  - pip=24.3.1
  - scikit-learn=1.4.1
  - matplotlib=3.8.3
  - plotly=5.19.0
  - pillow=10.2.0
  - mlflow=2.8.1
  - hydra-core=1.0.6
  - pip:
      - wandb==0.16.4
      - omegaconf==2.3.0
      - databricks_cli==0.18.0